[workspace]
channels = ["conda-forge"]
name = "livestock_mortality"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.3,<3"
numpy = ">=2.4.1,<3"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
jupyter = ">=1.1.1,<2"
